// angular/src/app/app.component.ts
import { Component, ViewChild, ElementRef, OnInit } from '@angular/core';

import './web-component';

@Component({
  selector: 'app-angular',
  template: `
    <rms-login
      #login
      name="Angular App"
      [type]="type"
      (loginAttempt)="onLoginAttempt($event)"
    >
    </rms-login>
  `
})
export class AppComponent implements OnInit {
  public type = 'angular';

  @ViewChild('login') private _loginComponent: ElementRef<HTMLRmsLoginElement>;

  public ngOnInit(): void {
    this._setEmail('angular@input.com');
  }

  public onLoginAttempt(
    event: CustomEvent<{ email: string; password: string }>
  ): void {
    console.log('Angular login attempt:', event.detail);
  }

  private _setEmail(email: string): void {
    this._loginComponent.nativeElement.email = email;
  }
}

// react/src/App.js
import React from 'react';
import { wc } from './utils/webcomponent';

function App() {
  const onLoginAttempt = event =>
    console.log('React login attempt:', event.detail);
  const email = 'react@input.com';

  return (
    <rms-login
      name="React App"
      type="react"
      email={email}
      ref={wc({
        loginAttempt: onLoginAttempt
      })}
    />
  );
}

export default App;
