// vue/src/App.vue
<template>
  <rms-login name="Vue App" type="vue" v-bind:email.prop="email" v-on:loginAttempt="loginAttempt"></rms-login>
</template>

<script>
export default {
  name: "app",
  data: () => ({
    email: "vue@prop.com",
    loginAttempt: event => console.log("Vue login attempt:", event.detail)
  })
};
</script>

// react/src/App.js
import React from 'react';
import { wc } from './utils/webcomponent';

function App() {
  const onLoginAttempt = event =>
    console.log('React login attempt:', event.detail);
  const email = 'react@input.com';

  return (
    <rms-login
      name="React App"
      type="react"
      email={email}
      ref={wc({
        loginAttempt: onLoginAttempt
      })}
    />
  );
}

export default App;
